# Spawn coords when logging to the lobby
# Using wrong worlds or invalid coords (Ex: Strings in coords) will cause
# Plugin exception
spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
  world: world
mainLobby: ""
# If you would like to generate a custom skin, you should go through this website
# https://mineskin.org
selector:
  selectorName:
    gamemode: ""
    subGamemode: ""
    skin: ""
    signature: ""
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    perk: false
board:
  default: true