authentication:
  enabled: false                                # Enabled when server is used for authentication
  redirect: main_lobby                          # PermissionGroup of servers where redirect after authentication
  coords:                                       # Teleport coordinates when session login
    x: 0
    y: 0
    z: 0
    world: world
    yaw: 0
    pitch: 0
announcement:
  enabled: false                                 # This will display announcements to everyone
  delay: 60                                      # This is the time in seconds that will delay between every announcement
  announcements:                                 # Write the key of the translation that you have written in language files
    - ""
    - ""